#!/bin/bash

# Get the primary Wi-Fi interface name (typically en0, but this ensures accuracy)
#WIFI_INTERFACE=$(networksetup -listallhardwareports | awk '/Wi-Fi|AirPort/{getline; print $2}')

#Parameters
if [ -z "$4" ]; then
	debug=false 
else
	debug=$4
fi

##Functions
getAutoProxyURL() {
	# Detects all network hardware & creates services for all installed network hardware
	/usr/sbin/networksetup -detectnewhardware
	
	IFS=$'\n'
	
	#Loops through the list of network services
	for i in $(networksetup -listallnetworkservices | tail +2 );
	do
		
		# Get a list of all services
		autoProxyURLLocal=`/usr/sbin/networksetup -getautoproxyurl "$i" | head -1 | cut -c 6-`
		
		# Echo's the name of any matching services & the autoproxyURL's set
		echo "$i Proxy set to $autoProxyURLLocal"
	done
	unset IFS
}
## MAIN
$debug && echo "debug mode enabled"

if $debug; then
	echo "report existing getautoproxyurl state"
	getAutoProxyURL
	echo ""
fi
# Disable Automatic Proxy Configuration
#networksetup -setautoproxyurl "Wi-Fi" ""
echo "update autoproxystate set values to off"
networksetup -setautoproxystate "Wi-Fi" off
networksetup -setautoproxystate "USB 10/100/1000 LAN" off
if $debug; then
	echo "report updated getproxyurl state"
	getAutoProxyURL 
	echo ""
fi
echo "Automatic Proxy Configuration removed for interface: Wi-Fi"
